version: '3'

services:

  web:
    # image: hardiklogicrays/microservices:v4

    build: .

    container_name: website

    # command: python3 manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/usr/src/app

    ports:
      - "8080:8000"

    depends_on:
      - db
    command: >
      sh -c "python3 manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres
    container_name: database

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
